// Jenkinsfile for MLBParks
podTemplate(
  label: "skopeo-pod",
  cloud: "openshift",
  inheritFrom: "maven",
  containers: [
    containerTemplate(
      name: "jnlp",
      image: "docker-registry.default.svc:5000/frodrigu-jenkins/jenkins-slave-maven-centos7",
      resourceRequestMemory: "1Gi",
      resourceLimitMemory: "2Gi"
    )
  ]
) {
  node('skopeo-pod') {
    def GUID = "frodrigu"
    echo "GUID: ${GUID}"
    git 'https://github.com/franredhat/appdev-mitzicom.git'
    echo "Packaging MLBParks"
    sh "cd MLBParks"
    sh "mvn -s ../nexus_settings.xml clean package -DskipTests=true"
    echo "MLBParks unit tests"
    sh "mvn -s ../nexus_settings.xml test"
    
    echo "Running MLBParks Code Analyses"
    sh "mvn -s ../nexus_settings.xml deploy -DskipTests=true -DaltDeploymentRepository=nexus::default::http://nexus-$GUID-nexus.apps.na39.openshift.opentlc.com/repository/releases"

    echo "Building container image MLBParks:0.0-0"
    sh "oc start-build mlbparks --follow --from-file=./target/${project.artifactId} -n ${GUID}-parks-dev"
    openshiftTag alias: 'false', destStream: 'MLBParks', destTag: 0.0-0, destinationNamespace: "${GUID}-parks-dev", namespace: "${GUID}-parks-dev", srcStream: 'MLBParks', srcTag: 'latest', verbose: 'false'

    echo "Publishing MLBParks to Nexus"
    sh "mvn -s ../nexus_settings.xml deploy -DskipTests=true -DaltDeploymentRepository=nexus::default::http://nexus-${GUID}-nexus.apps.na39.openshift.opentlc.com/repository/releases"

    echo "Deploying container image to Development Project"
    sh "oc set image dc/mlbparks mlbparks=docker-registry.default.svc:5000/${GUID}-parks-dev/mlbparks:0.0-0 -n ${GUID}-parks-dev"
    openshiftDeploy depCfg: 'mlbparks', namespace: "${GUID}-parks-dev", verbose: 'false', waitTime: '', waitUnit: 'sec'

    echo "Running integration tests"
    curl "http://mlbparks-${GUID}-parks-dev.apps.na39.openshift.opentlc.com/ws/data/load/" 
  }
}

// Convenience Functions to read variables from the pom.xml
// Do not change anything below this line.
def getVersionFromPom(pom) {
  def matcher = readFile(pom) =~ '<version>(.+)</version>'
  matcher ? matcher[0][1] : null
}
def getGroupIdFromPom(pom) {
  def matcher = readFile(pom) =~ '<groupId>(.+)</groupId>'
  matcher ? matcher[0][1] : null
}
def getArtifactIdFromPom(pom) {
  def matcher = readFile(pom) =~ '<artifactId>(.+)</artifactId>'
  matcher ? matcher[0][1] : null
}
