// Jenkinsfile for MLBParks
podTemplate(
  label: "skopeo-pod",
  cloud: "openshift",
  inheritFrom: "maven",
  containers: [
    containerTemplate(
      name: "jnlp",
      image: "docker-registry.default.svc:5000/frodrigu-jenkins/jenkins-slave-maven-centos7:v3.9",
      resourceRequestMemory: "1Gi",
      resourceLimitMemory: "2Gi"
    )
  ]
) {
  node('skopeo-pod') {
    def GUID = "frodrigu"
    def devTag  = "0.0-0"
    def prodTag = "0.0"
    
    stage('Nexus Needed Configuration for the Artifacts Generated') {
      echo "GUID: ${GUID}"
      echo "---> Wolfgang Nexus configuration"
      sh "curl -o setup_nexus3.sh -s https://raw.githubusercontent.com/wkulhanek/ocp_advanced_development_resources/master/nexus/setup_nexus3.sh"
      sh "chmod +x setup_nexus3.sh"
      sh "./setup_nexus3.sh admin admin123 http://nexus3-${GUID}-nexus.apps.na39.openshift.opentlc.com"
      sh "rm setup_nexus3.sh"
    }
    
    stage('Checkout Source') {
      git 'https://github.com/franredhat/appdev-mitzicom.git'
    }
    
    echo "Changing to MLBParks dir"
    dir ('MLBParks') {
      
      stage('Build war') {
        sh 'pwd; ls'
        echo "Packaging MLBParks"
        sh "mvn -s ../nexus_settings.xml clean package -DskipTests=true"
      }
      
      stage('Unit Tests') {
        echo "MLBParks unit tests"
        sh "mvn -s ../nexus_settings.xml test"    
      }
      
      stage('Publish to Nexus') {
        echo "Publishing MLBParks to Nexus"
        sh "mvn -s ../nexus_settings.xml deploy -DskipTests=true -DaltDeploymentRepository=nexus::default::http://nexus3-${GUID}-nexus.apps.na39.openshift.opentlc.com/repository/releases"
      }
      
      stage('Build and Tag OpenShift Image') {
        echo "Building container image MLBParks:0.0-0"
        sh "ls ./target/ | grep .war"
        sh "oc start-build mlbparks --follow --from-file=./target/mlbparks.war -n ${GUID}-parks-dev"
        openshiftTag alias: 'false', destStream: 'mlbparks', destTag: devTag, destinationNamespace: "${GUID}-parks-dev", namespace: "${GUID}-parks-dev", srcStream: 'mlbparks', srcTag: 'latest', verbose: 'false'
      }
      
      stage('Deploy to Dev') {
        echo "Deploying container image to Development Project"
        sh "oc set image dc/mlbparks mlbparks=docker-registry.default.svc:5000/${GUID}-parks-dev/mlbparks:${devTag} -n ${GUID}-parks-dev"
        openshiftDeploy depCfg: 'mlbparks', namespace: "${GUID}-parks-dev", verbose: 'false', waitTime: '', waitUnit: 'sec'
      }
      
      stage ('Setting Environment Variables') {
        echo "Setting Environment Variables"
        sh "oc set env dc/mlbparks --from=configmap/env"
        sh "oc rollout latest dc/mlbparks"
      }
      
      stage('Waiting to launch Integration Tests') {
        sleep 90
      }
      
      stage('Setting Up Integration Tests') {
        echo "Configuring integration tests"
        sh "oc label svc mlbparks type=parksmap-backend"
        sh 'curl "http://mlbparks-${GUID}-parks-dev.apps.na39.openshift.opentlc.com/ws/data/load/"'
      }
    }
  }
}
