kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "nationalparks-pipeline"
spec:
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: https://raw.githubusercontent.com/franredhat/appdev-mitzicom/master/MLBParks/Jenkinsfile
    type: JenkinsPipeline
