kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "parksmap-pipeline"
spec:
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: https://raw.githubusercontent.com/franredhat/appdev-mitzicom/master/ParksMap/Jenkinsfile
type: JenkinsPipeline
